data_dir: "/mnt/datadrive/noaa/"
filename: '2017_NOAA_ANWR_4Band3.TIF'
run_name: 'unmasked_dice'
window_size: [512,512]
model_opts:
  args: 
    inchannels: 4
    outchannels: 2
    net_depth: 3
    dropout: 0.3
    spatial: True
    first_channel_output: 4
optim_opts:
  name: "Adam"
  args:
    lr: 0.001
reg_opts:
  l1_reg: 0.0005