data_dir: "/mnt/datadrive/noaa/"
batch_size: 64
run_name: "masked_dice"
epochs: 51
save_every: 10
loss_opts:
  name: "dice"
  masked: True
  weights: None
  label_smoothing: 0.2
model_opts:
  args: 
    inchannels: 4
    outchannels: 2
    net_depth: 3
    dropout: 0.3
    spatial: True
    first_channel_output: 4
optim_opts:
  name: "Adam"
  args:
    lr: 0.001
log_opts:
  mask_names: ["Land", "Water"]
reg_opts:
  l1_reg: 0.0005
metrics_opts:
  IoU:
    threshold: 0.4
  pixel_acc:
    threshold: 0.4
  precision:
    threshold: 0.4
  recall:
    threshold: 0.4
  dice:
    threshold: 0.4