data_dir: "/datadrive/DynamicEarthNet"
satellite: "planet_test"
zone: "10N"
cubeid: "1311_3077_13"
filename: '2018-01-01.tif'
run_name: '7_channels_weighted'
model_opts:
  args: 
    inchannels: 9
    outchannels: 2
    net_depth: 5
    dropout: 0.3
    spatial: True
    first_channel_output: 64
optim_opts:
  name: "Adam"
  args:
    lr: 0.001
reg_opts:
  l1_reg: 0.0005
add_ndvi: True
add_ndwi: True
add_ndswi: True
add_evi2: True
add_osavi1: True
use_channels: [0,1,2,3,4,5,6,7,8]