data_dir: "/datadrive/DynamicEarthNet/"
class_name: "Snow"
batch_size: 4
run_name: "Snow"
epochs: 11
save_every: 5
use_channels: [0,1,2,3,4,5,6,7,8]
loss_opts:
  name: "dice"
  masked: True
  weights: [1.41683917, 1] # Snow Augmented
  # [1.98757861, 1] # Agriculture Augmented
  # [1, 1.02404193] # Forest Augmented
  # [7.63886255, 1] # Impervious Augmented
  # [17.25716061, 1] # Wetlands Augmented
  # [1.1308822, 1] # Soil Augmented
  # [22.47618135,  1] # Water Augmented
  # [1.41683917, 1] # Snow Augmented
  label_smoothing: 0.1
model_opts:
  args: 
    inchannels: 9
    outchannels: 2
    net_depth: 5
    dropout: 0.0001
    spatial: True
    first_channel_output: 64
optim_opts:
  name: "Adam"
  args:
    lr: 0.000001
log_opts:
  mask_names: ["Snow"]
reg_opts:
  l1_reg: 0.00005
metrics_opts: ["IoU", "precision", "recall"]